### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-atom-syntax#1]
:atom: 📦 ❤️ 
This epic tracks issues for optimized support implementations of the most popular Atom language packages.
I'm happy for any help and improvement suggestions, please feel free to create a PR or report issues.
## 💬 Community
- [x] <img src="https://avatars1.githubusercontent.com/u/2313237" width=16 height=16/>  [`language-babel`](https://atom.io/packages/language-babel) by [gandm](https://github.com/gandm) (@arcticicestudio, #8, 4ca659bf80a99853f24552e1428dd0d9a8ca7b15) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
  - [ES2016](https://babeljs.io)
  - [ESNext](https://github.com/esnext/esnext)
  - <img src="https://atom.io/favicon.ico" width=16 height=16/> Atom's [Etch](https://github.com/atom/etch)
  - <img src="https://facebook.com/favicon.ico" width=16 height=16/> Facebook's <img src="https://facebook.github.io/react/favicon.ico" width=16 height=16/> [React](https://facebook.github.io/react), <img src="https://flowtype.org/static/favicon.png" width=16 height=16/> [Flow](https://flowtype.org) and <img src="http://graphql.org/img/favicon.png" width=16 height=16/> [GraphQL](http://graphql.org)
- [x] <img src="https://avatars0.githubusercontent.com/u/1481354" width=16 height=16/>  [`language-elixir`](https://atom.io/packages/language-elixir) by [elixir-lang](https://github.com/elixir-lang) (@skbolton, #33, b141369c03) :package: :label: [0.5.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.5.0)
- [x] <img src="https://avatars2.githubusercontent.com/u/529516" width=16 height=16/>  [`language-diff`](https://atom.io/packages/language-diff) by [miketheman](https://github.com/miketheman) (@arcticicestudio, #34) :package: :label: [0.7.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.7.0)
- [x] <img src="https://avatars3.githubusercontent.com/u/569817" width=16 height=16/>  [`language-glsl`](https://atom.io/packages/language-glsl) by [hughsk](https://github.com/hughsk) (@arcticicestudio, #24, bc8268dc53864ad1a259a5a3234b6a935bf41100) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] <img src="https://avatars0.githubusercontent.com/u/6979737" width=16 height=16/>  [`language-haml`](https://atom.io/packages/language-haml) by [ezekg](https://github.com/ezekg) (@arcticicestudio, #22, 0651543f7a2d17f362079d630656469f382db4c8) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] <img src="https://avatars3.githubusercontent.com/u/12533767" width=16 height=16/>  [`language-haskell`](https://atom.io/packages/language-haskell) by [atom-haskell](https://github.com/atom-haskell) (@arcticicestudio, #21, 6ce40f2aeba0521f1842a1ab4b40aa02694e2a02) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] <img src="https://avatars2.githubusercontent.com/u/743164" width=16 height=16/> [`language-julia`](https://atom.io/packages/language-julia) by [JuliaLang](https://github.com/JuliaLang) (@arcticicestudio, #23, 61eec2ca99fa5018d1f9f67980bb24a8e114ba1d) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] <img src="https://avatars0.githubusercontent.com/u/1382556" width=16 height=16/> [`language-restructuredtext`](https://atom.io/packages/language-restructuredtext) by [Lukasa](https://github.com/Lukasa) (@arcticicestudio, #37) :package: :label: [0.7.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.7.0)

## ⚛️  Core
- [x] [`language-c`](https://atom.io/packages/language-c) (@arcticicestudio, #14, 7568bfbf68d1ea6ad06db8389f1f15756718e2b4) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-clojure`](https://atom.io/packages/language-clojure) (@arcticicestudio, #20, 42536fdb3181791ed020166ad60c9a607c90e942) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-coffee-script`](https://atom.io/packages/language-coffee-script) (@arcticicestudio, #18, 479df6a9be8e5e56c09e5b32a5a7f3374d34cc97) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-csharp`](https://atom.io/packages/language-csharp) (@arcticicestudio, #19, e532cf84b4a73c9e00e27ad1b948957c8ff8b438) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-css`](https://atom.io/packages/language-css) (@arcticicestudio, #5, a490f00c85b79f807bc26190fe45654fda34f358) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-gfm`](https://atom.io/packages/language-gfm) (@arcticicestudio, #6, 0ed29546b5b69059b3f488bee1a13b54d1c129ec) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-go`](https://atom.io/packages/language-go) (@arcticicestudio, #9, 8e5c242a) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-java`](https://atom.io/packages/language-java) (@arcticicestudio, #7, 513ec446) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
  - Includes the `.source.java-properties` CSS class scope
- [x] [`language-javascript`](https://atom.io/packages/language-javascript) (@arcticicestudio, #8, 4ca659bf80a99853f24552e1428dd0d9a8ca7b15) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-json`](https://atom.io/packages/language-json) (@arcticicestudio, #12, 0fe803a123326f883458ffc8e6e1c5582dc7db34) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-less`](https://atom.io/packages/language-less) (@arcticicestudio, #5 / #13, a490f00c85b79f807bc26190fe45654fda34f358 / 3fa1c27c28d056d8ca7babd95b2c2b5fea8045e3) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-php`](https://atom.io/packages/language-php) (@arcticicestudio, #17, 5d7d3565944b97b4a824df1f7bac3102f23b31db) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-python`](https://atom.io/packages/language-python) (@arcticicestudio, #11, 6b8f87c0f3ce800cada4bf551d59e0ffed834596) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-ruby`](https://atom.io/packages/language-ruby) (@arcticicestudio, #10, 972b90c4578c0bf91a3ed1a9de0554f57920191b) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-sass`](https://atom.io/packages/language-sass) (@arcticicestudio, #5, a490f00c85b79f807bc26190fe45654fda34f358) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-scala`](https://atom.io/packages/language-scala) (@arcticicestudio, #7, 513ec446bb0a21c32310bcc4e3874580ecfd441a) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-shellscript`](https://atom.io/packages/language-shellscript) (@arcticicestudio, #16, badfcc2b182211ef21f3e25d9ffd8628e63deb1f) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-yaml`](https://atom.io/packages/language-yaml) (@arcticicestudio, #15, 883ab296a249e6b9b93659724b5d2f2a37768854) :package: :label: [0.1.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.1.0)
- [x] [`language-xml`](https://atom.io/packages/language-xml) (@arcticicestudio, #29, a442b356) :package: :label: [0.4.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.4.0)

---

📦 Released APM package
🏷 Version tag

**Comment by arcticicestudio** [comment]
Resolved tasks:

### <img src="https://avatars0.githubusercontent.com/u/1089146" width=16 height=16/> Core
  - [x] [`language-css`](https://atom.io/packages/language-css)
  - [x] [`language-css`](https://atom.io/packages/language-css)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### Community
  - [x] <img src="https://avatars3.githubusercontent.com/u/12533767" width=16 height=16/>  [`language-haskell`](https://atom.io/packages/language-haskell)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### <img src="https://avatars0.githubusercontent.com/u/1089146" width=16 height=16/> Core
  - [x] [`language-xml`](https://atom.io/packages/language-xml)

**Comment by skbolton** [comment]
Amazing job on this syntax I am really loving it! I would like to see small tweaks added for Elixir. Would you be interested in a PR that adds Elixir Support?

**Comment by arcticicestudio** [comment]
Nice to hear you like it 😄 
I've already implemented some optimized styles for Elixir some weeks ago, but haven't created a issue & branch for it yet (local only, shame on me 😃).
I'll push it so you can test if it whether it meets your expectations and of course suggest improvements or add missing styles as PR to it.

**Comment by skbolton** [comment]
sounds great!

**Comment by arcticicestudio** [comment]
Resolved tasks:

### Community
  - [x] <img src="https://avatars0.githubusercontent.com/u/1481354" width=16 height=16/>  [`language-elixir`](https://atom.io/packages/language-elixir), 🚢 shipped in apm package release version [0.5.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.5.0)

**Comment by arcticicestudio** [comment]
Resolved tasks:

### 💬 Community
  - [x] <img src="https://avatars2.githubusercontent.com/u/529516" width=16 height=16/>  [`language-diff`](https://atom.io/packages/language-diff) :package: :label: [0.7.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.7.0)
  - [x] <img src="https://avatars0.githubusercontent.com/u/1382556" width=16 height=16/> [`language-restructuredtext`](https://atom.io/packages/language-restructuredtext) :package: :label: [0.7.0](https://github.com/arcticicestudio/nord-atom-syntax/releases/tag/v0.7.0)

**Comment by arcticicestudio** [comment]
Closing this issue now, special styles for many package are now obsolete since all tasks have been done and the Atom core theme API changed a lot and improved the default behavior on how packages adapt to the enabled theme.

Future optimizations/language supports will be resolved with one issues/language including the associated pull request.
